export const GET_SYSTEMS_CINEMA = "GET_SYSTEMS_CINEMA";
export const LAYT_THONG_TIN_LICH_CHIEU_PHIM = "LAYT_THONG_TIN_LICH_CHIEU_PHIM";
export const GET_LIST_LOGO_HE_THONG_RAP = "GET_LIST_LOGO_HE_THONG_RAP";
