export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_MOVIE_COMING_SOON = "GET_LIST_MOVIE_COMING_SOON";
export const GET_LIST_MOVIE_DANG_CHIEU = "GET_LIST_MOVIE_DANG_CHIEU";
export const LAY_THONG_TIN_PHIM = "LAY_THONG_TIN_PHIM";
