export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const GET_INFO_USER = "GET_INFO_USER";
export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const LAY_THONG_TIN_NGUOI_DUNG = "LAY_THONG_TIN_NGUOI_DUNG";
